scrape_configs:
  - job_name: 'Spring Boot Product Service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:9002']
        labels:
          application: 'My Spring Boot Application'